{{- if and .Values.global.apiserver.enabled .Values.global.apiserver.hvpa.enabled }}
{{- /* .Values.global.apiserver.replicaCount is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.global.apiserver.replicaCount | toString) "0" }}
apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: Hvpa
metadata:
  name: gardner-apiserver-hvpa
  namespace: garden
  labels:
    app: gardener
    role: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
{{- if .Values.global.apiserver.hvpa.maintenanceWindow }}
  maintenanceTimeWindow:
{{ toYaml .Values.global.apiserver.hvpa.maintenanceWindow | indent 4 }}
{{- end }}
  scaleUp:
    updatePolicy:
      updateMode: "Auto"
{{- if .Values.global.apiserver.hvpa.scaleUpstabilization }}
{{ toYaml .Values.global.apiserver.hvpa.scaleUpstabilization | indent 4 }}
{{- end }}
  scaleDown:
    updatePolicy:
      updateMode: "Auto"
{{- if .Values.global.apiserver.hvpa.scaleDownstabilization }}
{{ toYaml .Values.global.apiserver.hvpa.scaleDownstabilization | indent 4 }}
{{- end }}
  hpa:
    selector:
      matchLabels:
        role: gardener-apiserver-hpa
    deploy: false
    template:
      metadata:
        labels:
          role: gardener-apiserver-hpa
      spec:
        maxReplicas: {{ .Values.global.apiserver.hvpa.maxReplicas }}
        minReplicas: {{ .Values.global.apiserver.hvpa.minReplicas }}
        metrics:
        - resource:
            name: memory
            targetAverageUtilization: {{ .Values.global.apiserver.hvpa.targetAverageUtilizationMemory }}
          type: Resource
        - resource:
            name: cpu
            targetAverageUtilization: {{ .Values.global.apiserver.hvpa.targetAverageUtilizationCpu }}
          type: Resource
  vpa:
    selector:
      matchLabels:
        role: gardener-apiserver-vpa
    deploy: true
{{- if .Values.global.apiserver.hvpa.limitsRequestsGapScaleParams }}
    limitsRequestsGapScaleParams:
{{ toYaml .Values.global.apiserver.hvpa.limitsRequestsGapScaleParams | indent 6 }}
{{- end }}
    template:
      metadata:
        labels:
          role: gardener-apiserver-vpa
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: gardener-apiserver
              maxAllowed:
                memory: 32G
                cpu: "8"
              minAllowed:
                memory: 400M
                cpu: 400m
  scaleIntervals:
    - maxReplicas: 1
      maxCpu: 0.5
      maxMemory: 2
    - maxReplicas: 2
      maxCpu: 1
      maxMemory: 4
    - maxReplicas: 3
      maxCpu: 2
      maxMemory: 8
    - maxReplicas: 4
      maxCpu: 4
      maxMemory: 16
    - maxReplicas: 5
      maxCpu: 8
      maxMemory: 32
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: gardener-apiserver
{{ end }}
{{ end }}
