{{ if .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: Hvpa
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
{{- if .Values.maintenanceWindow }}
  maintenanceTimeWindow:
{{ toYaml .Values.maintenanceWindow | indent 4 }}
{{- end }}
  scaleUp:
    updatePolicy:
      updateMode: "Auto"
{{- if .Values.scaleUpStabilization }}
{{ toYaml .Values.scaleUpStabilization | indent 4 }}
{{- end }}
  scaleDown:
    updatePolicy:
      updateMode: "Auto"
{{- if .Values.scaleDownStabilization }}
{{ toYaml .Values.scaleDownStabilization | indent 4 }}
{{- end }}
  hpa:
    selector:
      matchLabels:
        role: apiserver-hpa
    deploy: false
    template:
      metadata:
        labels:
          role: apiserver-hpa
      spec:
        maxReplicas: {{ .Values.maxReplicas }}
        minReplicas: {{ .Values.minReplicas }}
        metrics:
{{- if .Values.hpa.memoryMetricForHpaEnabled }}
        - resource:
            name: memory
            targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationMemory }}
          type: Resource
{{- end }}
        - resource:
            name: cpu
            targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationCpu }}
          type: Resource
  vpa:
    selector:
      matchLabels:
        role: apiserver-vpa
    deploy: true
{{- if .Values.limitsRequestsGapScaleParams }}
    limitsRequestsGapScaleParams:
{{ toYaml .Values.limitsRequestsGapScaleParams | indent 6 }}
{{- end }}
    template:
      metadata:
        labels:
          role: apiserver-vpa
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: kube-apiserver
              maxAllowed:
                memory: 32G
                cpu: "8"
              minAllowed:
                memory: 400M
                cpu: 300m
            - containerName: vpn-seed
              mode: "Off"
  scaleIntervals:
    - maxReplicas: 1
      maxCpu: "0.4"
      maxMemory: 1G
    - maxReplicas: 2
      maxCpu: "0.6"
      maxMemory: 1.5G
    - maxReplicas: 3
      maxCpu: "0.8"
      maxMemory: 2G
    - maxReplicas: 4
      maxCpu: "1"
      maxMemory: 2.75G
    - maxReplicas: 5
      maxCpu: "1.5"
      maxMemory: 4G
    - maxReplicas: 6
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: kube-apiserver
{{ end }}
{{ end }}
